config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "public#index"
  
  resources :posts
  resources :events

  get "/emt", to: "emt#index"
  namespace :emt do
    resources :workshops
    resources :teachers
    resources :instruments
  end

  get "/groupement", to: "groupement#index"
  get "/events", to: "events#index"
  get "/bogue", to: "events#bogue"
  get "/events/:id", to: "events#show"

  get "/centre-de-ressources", to: "resources#index", as: "resources"
  get "/centre-de-ressources/editions", to: "resources#editions", as: "editions"
  get "/centre-de-ressources/editions/:id", to: "resources#edition", as: "edition"

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  namespace :secretariat do
    root to: "students#index"

    resources :students
    resources :subscriptions
    resources :teachers
    resources :instruments
    resources :instrument_classes
    resources :sessions
    resources :workshops
    resources :seasons
    resources :plans
    resources :cities

    resources :events
    resources :posts
    resources :categories
    resources :editions

  end
  
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: true
  validates :start_date, presence: true
  validates :city, presence: true
  
  validates_comparison_of :end_date, greater_than_or_equal_to: :start_date

  has_many :posts
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  def bogue
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :content, :start_date, :end_date, :address_first, :address_second, :street, :city)
    end
end

app/controllers/secretariat/events_controller.rb
module Secretariat
  class EventsController < Secretariat::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= event.content %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= event.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= event.end_date %>
  </p>

  <p>
    <strong>Address first:</strong>
    <%= event.address_first %>
  </p>

  <p>
    <strong>Address second:</strong>
    <%= event.address_second %>
  </p>

  <p>
    <strong>Street:</strong>
    <%= event.street %>
  </p>

  <p>
    <strong>City:</strong>
    <%= event.city %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.datetime_field :end_date %>
  </div>

  <div>
    <%= form.label :address_first, style: "display: block" %>
    <%= form.text_field :address_first %>
  </div>

  <div>
    <%= form.label :address_second, style: "display: block" %>
    <%= form.text_field :address_second %>
  </div>

  <div>
    <%= form.label :street, style: "display: block" %>
    <%= form.text_field :street %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/bogue.html.erb
<% content_for(:page_title, "La Bogue d’Or") %>
<% content_for(:page_class, "bogue") %>

<%= render Global::HeroComponent.new(title: "La Bogue d’Or") %>

<section class="section">
  <div class="wrapper wrapper--text text-container">
    <p>La Bogue d’Or a été créée à Redon il y a plus de 45 ans par des passionnés visionnaires, pour faire revivre le chant traditionnel local avec un concours de chant a capella, devenu au fil des ans un véritable festival !</p>

    <p>La Bogue d’Or propose concours de conte,  chant, musicaux (biniou-bombarde, duos libres..), fest-noz, Chicass’Noz, joute contée et chantée par équipe (avec vote du public !), apéros poétiques.</p>

    <p>Ici le dialogue des cultures fonctionne ! Jeunes et moins jeunes se côtoient sur scène ou dans la ronde, la culture locale flirte avec d’autres influences et on aime aussi découvrir d’autres cultures de tradition populaire.  
    La programmation se dévoile chaque année en période estivale... pour se préparer à danser lors des premières fraicheurs de l'automne !</p>

    <p>Organisé par le Groupement Culturel Breton des Pays de Vilaine, le festival se réinvente chaque année pour de nouveaux partages. Profondément ancré grâce aux racines, à la transmission des ainés, c'est un festival ouvert sur le monde qui puise dans toutes les traditions pour de savoureux mélanges sonores !</p>
  </div>
</section>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<% content_for(:page_title, "Événements") %>
<% content_for(:page_class, "events") %>

<%= render Global::HeroComponent.new(title: "Événements") %>

<section class="section">
  <div class="wrapper">
    <%= render Events::EventListComponent.new(events: @events) %>
  </div>
</section>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<% content_for(:page_title, @event.name) %>

<%= render Global::HeroComponent.new(title: @event.name) do |component| %>
  <% component.extra do %>
    <p class="hero__extra">
      <% if @event.end_date.present? %>
        <%= "Du #{I18n.l(@event.start_date, format: "%d %B %Y")} au #{I18n.l(@event.end_date, format: "%d %B %Y")}" %>
      <% else %>
        <%= "Le #{I18n.l(@event.start_date, format: "%d %B %Y")}" %>
      <% end %>
    </p>
  <% end %>
<% end %>

<section class="section">
  <div class="wrapper wrapper--text">
    <div class="text-container"><%= markdown(@event.content) %></div>

    <div>
      <%= link_to "Edit this event", edit_event_path(@event) %> |
      <%= link_to "Back to events", events_path %>

      <%= button_to "Destroy this event", @event, method: :delete %>
    </div>
  </div>
</section>